### PR TITLE
Alpha version - Edit: remove tags

### LINKED ISSUE #85: Alpha version - Edit: remove tags
Implement functionality to remove specific tags with edit command

### PR DESCRIPTION
**Pull request by sannie-beep**
fixes #85

### CODE REVIEW

**Comment by PrishaVP** [comment]
Can consider changing all occurrences of tag to studyGroupTag or something like that. Also I think you should look through EditCommandParserTest to see if you need to make any changes. For example, parse_allFieldsSpecified_success() could probably also include the remove tag field. then for parse_resetStudyGroupTags_success() maybe you can check whether it is still applicable now that there is a remove tag feature.

**Comment by sannie-beep** [comment]
> Mostly everything looks good but can consider changing all occurrences of tag to studyGroupTag or something like that. Also I think you should look through EditCommandParserTest to see if you need to make any changes. For example, parse_allFieldsSpecified_success() could probably also include the remove tag field. then for parse_resetStudyGroupTags_success() maybe you can check whether it is still applicable now that there is a remove tag feature.

I think I kept it as tag to reduce the lengths of the names of the different associated fields and methods, because it sounded a bit complicated. But yes, I'll edit the test file, thanks!

**Comment by sannie-beep** [comment]
> > Mostly everything looks good but can consider changing all occurrences of tag to studyGroupTag or something like that. Also I think you should look through EditCommandParserTest to see if you need to make any changes. For example, parse_allFieldsSpecified_success() could probably also include the remove tag field. then for parse_resetStudyGroupTags_success() maybe you can check whether it is still applicable now that there is a remove tag feature.
> 
> I think I kept it as tag to reduce the lengths of the names of the different associated fields and methods, because it sounded a bit complicated. But yes, I'll edit the test file, thanks!

Also, I think the parse_resetStudyGroupTags_success() is not applicable to the remove tags feature, and has been edited by those who worked on the add tag one already, since there's no functionality to reset the tags now.

**Comment by PrishaVP** [comment]
LGTM!

**Pull request merged**
